# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CSE 5539
semester: Fall 2026
university: The Ohio State University
tagline: Special Topics in Large Language Models (Fall 2026)
description: Special Topics in Large Language Models
author: Sachin Kumar
baseurl: '/cse-5539-fall-2026' # the subpath of your site, e.g. /blog
url: 'https://shocheen.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
logo: "/assets/images/osu-2.png"
kramdown:
  toc_levels: 1..2

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.8.2
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  "Canvas":
    - "https://osu.instructure.com/courses/219498"
  "Teams":
    - "https://teams.microsoft.com/l/team/19%3Am1Yif0euIagov96GEgqKtUKFPLuIZEU9ymMIEIcxQ6U1%40thread.tacv2/conversations?groupId=cc18a6b3-a224-40b6-8e5d-7b85857a791c&tenantId=eb095636-1052-4895-952b-1ff9df1d1121"
  "TopHat":
    - "https://app.tophat.com/e/434791"
footer_content:


# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
